### ISSUE TITLE
Use of deprecated C++ feature std::random_shuffle

### ISSUE THREAD

**Issue by yurivict** [trolando/oink#19]
[Here](https://github.com/trolando/oink/blob/master/test/test_solvers.cpp#L252).

You don't set the C++ standard level, so when the compiler defaults to C++20, the compilation fails:
```
/wrkdirs/usr/ports/math/oink/work/oink-3327c54/test/test_solvers.cpp:250:19: error: no member named 'random_shuffle' in namespace 'std'
        else std::random_shuffle(files.begin(), files.end());
             ~~~~~^
```

You should either explicitly use older than c++17 level, or replace deprecated features with available alternatives.

clang-16
FreeBSD 13.2

**Comment by trolando** [comment]
I have now fixed this.
