### ISSUE TITLE
Oink does not run on Centos 7

### ISSUE THREAD

**Issue by dpalmer895** [trolando/oink#6]
I have tried using oink on Centos 7 but although it builds successfully I get an error when I try to run it:

[dpalmer@blackrat ~]$ oink --help
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)

The exact version of Centos is:

[dpalmer@blackrat ~]$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

[dpalmer@blackrat ~]$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[dpalmer@blackrat build]$ cmake ..
-- OS: Linux
-- Compiler: GNU
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   filesystem
--   iostreams
--   regex
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dpalmer/oink/oink.git/trunk/build
[dpalmer@blackrat build]$

**Comment by trolando** [comment]
This issue is related to the gcc version that you use. Unfortunately the library I use cxxopts is incompatible with older gcc versions.

You need gcc 4.9, e.g. https://stackoverflow.com/questions/37411117/terminate-called-after-throwing-an-instance-of-stdregex-error

**Comment by trolando** [comment]
I have added commit 55c55d7ec65eb13e970e8530628bf16df84f44f2 which notifies the user if their compiler is too old.
