### ISSUE TITLE
Building Oink on Windows

### ISSUE THREAD

**Issue by kasperdokter** [trolando/oink#8]
I am a Windows user, and I would like to run the Oink solver for my research project. Unfortunately, there is no precompiled binary (.exe and .dll) for Windows available. I strongly recommend for the release of such a binary, to save others from going through the same trouble as I did:

First, I installed cmake and boost directly. Then cmake produces by default a Visual Studio Solution, which is supposed to compile with MSBuild. However, this compilation failed, because Oink includes 'sys/mman.h', which is a POSIX library without a Windows equivalent. 

Therefore, I tried to use Cygwin to build Oink. First, I installed Cygwin (https://cygwin.com/install.html), and installed the following packages:

```
mingw64-x86_64-gcc-core
mingw64-x86_64-gcc-g++
cmake
boost
```

I installed Boost 1.65.1 (https://www.boost.org/users/history/version_1_65_1.html) and build it via the Cygwin terminal in admin mode using the following commands: 

```
cd "C:\Program Files\Boost\boost_1_65_1"
./bootstrap.sh
./b2 link=static runtime-link=static release stage
```

Along the way, I tried different versions of Boost, but I could not even build Boost 1.75.0 from the Cygwin terminal (although the build via cmd.exe did succeed).  Then, I invoked cmake via the following command via the Cygwin terminal:

```
cmake -DBoost_USE_STATIC_LIBS=ON -DBOOST_ROOT:PATH="C:\Program Files\Boost\boost_1_65_1" ..
```

However, when I run `make` via the Cygwin terminal, I get the following output:

```
Scanning dependencies of target oink
[  3%] Building CXX object CMakeFiles/oink.dir/src/game.cpp.o
In file included from /cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/game.hpp:26,
                 from /cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/game.cpp:23:
/cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/bitset.hpp: In member function 'void pg::bitset::resize(size_t)':
/cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/bitset.hpp:132:77: error: 'MREMAP_MAYMOVE' was not declared in this scope
  132 |                 _bits = (uint64_t*)mremap(_bits, _allocsize, new_allocsize, MREMAP_MAYMOVE);
      |                                                                             ^~~~~~~~~~~~~~
/cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/bitset.hpp:132:36: error: 'mremap' was not declared in this scope; did you mean 'munmap'?
  132 |                 _bits = (uint64_t*)mremap(_bits, _allocsize, new_allocsize, MREMAP_MAYMOVE);
      |                                    ^~~~~~
      |                                    munmap
/cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/game.cpp: In member function 'void pg::Game::e_sizeup()':
/cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/game.cpp:918:85: error: 'MREMAP_MAYMOVE' was not declared in this scope
  918 |     _outedges = (int*)mremap(_outedges, sizeof(int[old]), sizeof(int[e_allocated]), MREMAP_MAYMOVE);
      |                                                                                     ^~~~~~~~~~~~~~
/cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/game.cpp:918:23: error: 'mremap' was not declared in this scope; did you mean 'munmap'?
  918 |     _outedges = (int*)mremap(_outedges, sizeof(int[old]), sizeof(int[e_allocated]), MREMAP_MAYMOVE);
      |                       ^~~~~~
      |                       munmap
/cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/game.cpp: In member function 'void pg::Game::v_sizeup()':
/cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/game.cpp:928:85: error: 'MREMAP_MAYMOVE' was not declared in this scope
  928 |     _priority = (int*)mremap(_priority, sizeof(int[old]), sizeof(int[v_allocated]), MREMAP_MAYMOVE);
      |                                                                                     ^~~~~~~~~~~~~~
/cygdrive/c/Users/Kasper/Documents/GitHub/oink/src/game.cpp:928:23: error: 'mremap' was not declared in this scope; did you mean 'munmap'?
  928 |     _priority = (int*)mremap(_priority, sizeof(int[old]), sizeof(int[v_allocated]), MREMAP_MAYMOVE);
      |                       ^~~~~~
      |                       munmap
make[2]: *** [CMakeFiles/oink.dir/build.make:83: CMakeFiles/oink.dir/src/game.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:154: CMakeFiles/oink.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

I do not see what I did wrong to get these errors. What can I do?

**Comment by trolando** [comment]
Did you try to use the WSL Windows Subsystem for Linux to build Oink?

There is no current official support for Windows, but if I would want to run it under Windows nowadays, I'd first start with using WSL and not Cygwin.

The mmap/munmap/mremap stuff may still be unsupported though. Basically you could just replace those with malloc/realloc calls, the reason I use mmap/mremap is for a very slight performance improvement.

**Comment by trolando** [comment]
Yeah I just ran it on Windows using WSL2 and Ubuntu 20.04 (default instructions you can find anywhere on the Internet) and after installing a couple of packages, like cmake, g++, libboost-all-dev, I could build and run Oink.
